version: "3"

services:
  pyspark:
    container_name: "pyspark"
    image: jupyter/pyspark-notebook
    ports:
      - "8888:8888"
      - "4040:4040"
    networks:
      - custom
    volumes:
      - ./storage/notebooks:/home/jovyan/work
      - ./storage/data:/home/jovyan/data

networks:
  custom:
    driver: bridge
